# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'uni_plannerYnFCFD.ui'
##
## Created by: Qt User Interface Compiler version 6.4.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QGroupBox, QLabel,
    QListWidget, QListWidgetItem, QMainWindow, QMenuBar,
    QPushButton, QSizePolicy, QStackedWidget, QStatusBar,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setFixedSize(QSize(1337, 670))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(10, 10, 1281, 351))
        self.stackedWidget.setMinimumSize(QSize(1281, 0))
        self.stackedWidgetPage1 = QWidget()
        self.stackedWidgetPage1.setObjectName(u"stackedWidgetPage1")
        self.monday_widget = QWidget(self.stackedWidgetPage1)
        self.monday_widget.setObjectName(u"monday_widget")
        self.monday_widget.setGeometry(QRect(61, 7, 246, 336))
        self.monday_1 = QWidget(self.monday_widget)
        self.monday_1.setObjectName(u"monday_1")
        self.monday_1.setGeometry(QRect(0, 0, 250, 48))
        self.monday_2 = QWidget(self.monday_widget)
        self.monday_2.setObjectName(u"monday_2")
        self.monday_2.setGeometry(QRect(0, 48, 250, 48))
        self.monday_3 = QWidget(self.monday_widget)
        self.monday_3.setObjectName(u"monday_3")
        self.monday_3.setGeometry(QRect(0, 96, 250, 48))
        self.monday_4 = QWidget(self.monday_widget)
        self.monday_4.setObjectName(u"monday_4")
        self.monday_4.setGeometry(QRect(0, 144, 250, 48))
        self.monday_5 = QWidget(self.monday_widget)
        self.monday_5.setObjectName(u"monday_5")
        self.monday_5.setGeometry(QRect(0, 192, 250, 48))
        self.monday_6 = QWidget(self.monday_widget)
        self.monday_6.setObjectName(u"monday_6")
        self.monday_6.setGeometry(QRect(0, 240, 250, 48))
        self.monday_7 = QWidget(self.monday_widget)
        self.monday_7.setObjectName(u"monday_7")
        self.monday_7.setGeometry(QRect(0, 288, 250, 48))
        self.widget_3 = QWidget(self.stackedWidgetPage1)
        self.widget_3.setObjectName(u"widget_3")
        self.widget_3.setGeometry(QRect(311, 10, 246, 336))
        self.time_widget = QWidget(self.stackedWidgetPage1)
        self.time_widget.setObjectName(u"time_widget")
        self.time_widget.setGeometry(QRect(0, 7, 61, 336))
        self.stackedWidget.addWidget(self.stackedWidgetPage1)
        self.stackedWidgetPage2 = QWidget()
        self.stackedWidgetPage2.setObjectName(u"stackedWidgetPage2")
        self.stackedWidget.addWidget(self.stackedWidgetPage2)
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 370, 811, 261))
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 20, 111, 16))
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(280, 20, 231, 16))
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(550, 20, 221, 20))
        self.listWidget_2 = QListWidget(self.groupBox)
        QListWidgetItem(self.listWidget_2)
        self.listWidget_2.setObjectName(u"listWidget_2")
        self.listWidget_2.setGeometry(QRect(280, 40, 231, 211))
        self.listWidget_2.setDragDropMode(QAbstractItemView.InternalMove)
        self.listWidget_4 = QListWidget(self.groupBox)
        QListWidgetItem(self.listWidget_4)
        self.listWidget_4.setObjectName(u"listWidget_4")
        self.listWidget_4.setGeometry(QRect(20, 40, 231, 211))
        self.listWidget_3 = QListWidget(self.groupBox)
        QListWidgetItem(self.listWidget_3)
        QListWidgetItem(self.listWidget_3)
        QListWidgetItem(self.listWidget_3)
        QListWidgetItem(self.listWidget_3)
        self.listWidget_3.setObjectName(u"listWidget_3")
        self.listWidget_3.setGeometry(QRect(550, 40, 231, 211))
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(254, 184, 175, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(255, 170, 255, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        brush3 = QBrush(QColor(254, 219, 215, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        brush4 = QBrush(QColor(127, 92, 87, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush4)
        brush5 = QBrush(QColor(169, 123, 117, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        brush6 = QBrush(QColor(255, 255, 255, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        brush7 = QBrush(QColor(255, 85, 255, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush7)
        brush8 = QBrush(QColor(255, 255, 220, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        brush9 = QBrush(QColor(0, 0, 0, 127))
        brush9.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush9)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush9)
#endif
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush7)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
        brush10 = QBrush(QColor(127, 92, 87, 127))
        brush10.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush10)
#endif
        self.listWidget_3.setPalette(palette)
        self.listWidget_3.setDragDropMode(QAbstractItemView.DragOnly)
        self.listWidget_3.setAlternatingRowColors(True)
        self.widget = QWidget(self.centralwidget)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(900, 390, 281, 211))
        self.label_4 = QLabel(self.widget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 20, 121, 16))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(910, 370, 281, 16))
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(1200, 560, 81, 41))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1337, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Selekcjonuj kursy", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Bardzo chc\u0119", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Oboj\u0119tne", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Bardzo nie chc\u0119", None))

        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        ___qlistwidgetitem = self.listWidget_2.item(0)
        ___qlistwidgetitem.setText(QCoreApplication.translate("MainWindow", u"Kurs1", None));
        self.listWidget_2.setSortingEnabled(__sortingEnabled)


        __sortingEnabled1 = self.listWidget_4.isSortingEnabled()
        self.listWidget_4.setSortingEnabled(False)
        ___qlistwidgetitem1 = self.listWidget_4.item(0)
        ___qlistwidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Nowy element", None));
        self.listWidget_4.setSortingEnabled(__sortingEnabled1)


        __sortingEnabled2 = self.listWidget_3.isSortingEnabled()
        self.listWidget_3.setSortingEnabled(False)
        ___qlistwidgetitem2 = self.listWidget_3.item(0)
        ___qlistwidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Nowy element", None));
        ___qlistwidgetitem3 = self.listWidget_3.item(1)
        ___qlistwidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Nowy element", None));
        ___qlistwidgetitem4 = self.listWidget_3.item(2)
        ___qlistwidgetitem4.setText(QCoreApplication.translate("MainWindow", u"Nowy element", None));
        ___qlistwidgetitem5 = self.listWidget_3.item(3)
        ___qlistwidgetitem5.setText(QCoreApplication.translate("MainWindow", u"Nowy element", None));
        self.listWidget_3.setSortingEnabled(__sortingEnabled2)

        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Nazwa kursu", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Informacje o kursie", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Wygeneruj", None))
    # retranslateUi


if __name__ == "__main__":

    app = QApplication()
    window = QMainWindow()
    Ui_MainWindow().setupUi(window)
    window.show()
    app.exec()